### ISSUE TITLE
TrackSelectionDialog

### ISSUE THREAD

**Issue by vista136** [mkalyon/cordova-plugin-mkExoplayer#2]
Can this plugin show the video setting like., Quality, Subtitles, and Audio ?

because the plugin Exoplayer 2.10.0 Up used dialogFragment to show it.,
and when i try.., always crash with cordova activity

**Comment by mkalyon** [comment]
I have used alert dialog method for subtitles and audios selection. Maybe can be add trackselectiondialog with ExoPlayer 2.11.x but I cant do it.
I will publish mkExoplayer plugin in this month

**Comment by mkalyon** [comment]
Published. You can test it

**Comment by vista136** [comment]
ok my friend..


Pada tanggal Kam, 10 Sep 2020 pukul 14.22 mkalyon <notifications@github.com>
menulis:
